name: Staging Deployment

on:
  push:
    branches: main

jobs:
  deploy:
    name: Deploy to Staging (CMS)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.4.6
        with:
          appdir: cms
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_STAGING_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
