name: Test trunk

on:
  push:
    branches: trunk
    
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.7
      - run: npm ci
      - run: npm test:e2e
        env:
          CI: true
