name: Test trunk
on:
  push:
    branches: trunk
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    container: node:10.18-jessie

    services:
      db:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Wait until postgres has started.
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout backend
        uses: actions/checkout@v2
        with:
          repository: 'joonashak/reclab-cms'
          path: cms

      - name: Set up node for backend
        uses: actions/setup-node@v1
        with:
          node-version: 14.8

      - name: Run CMS backend
        run: npm ci && npm run build && npm run start:prod &
        working-directory: cms
        env:
          NODE_ENV: test
          PORT: 3001
          DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
          JWT_SECRET: asd

      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: web
      - name: Cypress Run
        uses: cypress-io/github-action@v2
        with:
          working-directory: web
          build: curl http://127.0.0.1:3001/
          start: npm run serve
          wait-on: 'http://localhost:9000'
        env:
          CMS_URL: http://localhost:3001
