name: Test trunk
on:
  push:
    branches: trunk
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    container: node:10.18-jessie

    services:
      db:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Wait until postgres has started.
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      cms:
        image: docker.pkg.github.com/joonashak/reclab-cms/asd:0.0.4
        env:
          NODE_ENV: development
          PORT: 3001
          DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
          JWT_SECRET: asd
        # Wait until cms has started.
        options: >-
          --health-cmd curl -sS 127.0.0.1:3001 || exit 1
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress Run
        uses: cypress-io/github-action@v2
        with:
          build: curl http://cms:3001/
          start: npm run serve
          wait-on: 'http://localhost:9000'
        env:
          CMS_URL: http://localhost:3001
